# Generated by Django 3.0.8 on 2020-07-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0002_booking_route_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='total_seats',
        ),
        migrations.AddField(
            model_name='timing',
            name='total_seats',
            field=models.IntegerField(default=75),
        ),
    ]
